library(NSM3)
data(discrepancy.scores)
hist(discrepancy.scores)
library(MASS)
par(mfrow=c(1,3))
truehist(discrepancy.scores);hist(discrepancy.scores)
print(IQR<-IQR(discrepancy.scores))
print(n<-length(discrepancy.scores))
print(h<-2*IQR*(n^(-1/3)))
truehist(discrepancy.scores,nbins="ND",h)
# Scott method
print(h1<-3.5*sd(discrepancy.scores)*((length(discrepancy.scores))^(-1/3)))
truehist(discrepancy.scores,nbins="Scott",h1)
help("log")
#Sturges
print(m<-log(length(discrepancy.scores),base=exp(2))+1)
hist(discrepancy.scores,breaks = "Sturges")
help("truehist")
#Q2)
help("density")
par(mfrow=c(2,2))
lines(density(discrepancy.scores,bw=0.1443,kernel="gaussian"))
lines(density(discrepancy.scores,bw=0.1443,kernel= "epanechnikov"))
lines(density(discrepancy.scores,bw=0.1443,kernel="rectangular"))
lines(density(discrepancy.scores,bw=0.1443,kernel= "triangular"))
par(mfrow=c(4,2))

plot(density(discrepancy.scores, kernel="gaussian",bw=0.1443))
plot(density(discrepancy.scores, kernel="epanechnikov",bw=0.1443))
plot(density(discrepancy.scores, kernel="rectangular",bw=0.1443))
plot(density(discrepancy.scores, kernel="triangular",bw=0.1443))

plot(density(discrepancy.scores, kernel="gaussian",bw=0.005))
plot(density(discrepancy.scores, kernel="gaussian",bw=0.05))
plot(density(discrepancy.scores, kernel="gaussian",bw=0.14))
plot(density(discrepancy.scores, kernel="gaussian",bw=5))

#Q3)
par(mfrow=c(2,2))
plot(density(discrepancy.scores, kernel="gaussian",bw="nrd0"))
plot(density(discrepancy.scores,kernel="gaussian",bw= "nrd"))
plot(density(discrepancy.scores,kernel="gaussian",bw="ucv"))
plot(density(discrepancy.scores,kernel="gaussian",bw="bcv"))

